export const CITIES = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce",
] as const;

export const POPULAR_CITIES = [
  "İstanbul",
  "Ankara",
  "İzmir",
  "Bursa",
  "Antalya",
  "Adana",
  "Konya",
  "Gaziantep",
] as const;

export const EDUCATION_LABELS: Record<string, string> = {
  ilkokul: "İlkokul",
  ortaokul: "Ortaokul",
  lise: "Lise",
  onlisans: "Ön Lisans",
  lisans: "Lisans",
  yuksek_lisans: "Yüksek Lisans",
  doktora: "Doktora",
};

export const AVAILABILITY_LABELS: Record<string, string> = {
  hemen: "Hemen başlayabilirim",
  "1_hafta": "1 hafta içinde",
  "2_hafta": "2 hafta içinde",
  "1_ay": "1 ay içinde",
  esnek: "Esnek",
};

export const MILITARY_LABELS: Record<string, string> = {
  yapildi: "Yapıldı",
  tecilli: "Tecilli",
  muaf: "Muaf",
  yapilmadi: "Yapılmadı",
};

export const DRIVER_LICENSES = ["B", "C", "D", "E", "SRC"] as const;

export const LANGUAGES = [
  "Türkçe",
  "İngilizce",
  "Almanca",
  "Fransızca",
  "Arapça",
  "Rusça",
  "İspanyolca",
] as const;

export const SECTORS = [
  "Teknoloji",
  "İnşaat",
  "Üretim",
  "Sağlık",
  "Eğitim",
  "Turizm",
  "Lojistik",
  "Finans",
  "Perakende",
  "Enerji",
  "Tarım",
  "Hizmet",
  "Diğer",
] as const;

export const FAQ_ITEMS = [
  {
    q: "Patron Beni Kap nedir?",
    a: "İşçilerin profesyonel profil oluşturduğu, firmaların da bu profilleri hızlıca bulduğu modern bir platformdur. CV yüklemek zorunlu değil — birkaç dakikada profilini tamamla.",
  },
  {
    q: "Ücretsiz mi?",
    a: "Evet. Hem işçiler hem firmalar temel özellikleri ücretsiz kullanabilir.",
  },
  {
    q: "Profilimi kimler görebilir?",
    a: "Görünürlük ayarını sen kontrol edersin. Profilini gizleyebilir veya herkese açık tutabilirsin.",
  },
  {
    q: "Firma doğrulaması nasıl yapılır?",
    a: "Firmalar kayıt olduktan sonra ekip doğrulama sürecinden geçer. Doğrulanan firmalar rozet alır.",
  },
  {
    q: "Nasıl mesajlaşırım?",
    a: "Firmalar ilgilendiği işçilere mesaj atabilir. Gerçek zamanlı sohbet ile hızlıca iletişim kurarsın.",
  },
] as const;

export const TESTIMONIALS = [
  {
    name: "Ayşe Yılmaz",
    role: "Grafik Tasarımcı",
    text: "Profilimi 5 dakikada oluşturdum. İki gün sonra 3 firmadan mesaj geldi. Gerçekten iş beni buldu.",
    city: "İstanbul",
  },
  {
    name: "Mehmet Kaya",
    role: "İnsan Kaynakları Müdürü",
    text: "Kariyer sitelerindeki karmaşadan bıktık. Burada filtreleyip doğru kişiyi dakikalar içinde buluyoruz.",
    city: "Ankara",
  },
  {
    name: "Can Demir",
    role: "Elektrikçi",
    text: "WhatsApp ve telefonum profilimde. Firmalar direkt ulaşıyor. Çok pratik.",
    city: "İzmir",
  },
] as const;
